Tyshchenko/rvat 645 check present change button
Social-projects-Rivne/GreenTourism_ATests pull request #23
Opened 2016-12-22 14:58 UTC by TyshchenkoRoma

2016-12-22 16:38 UTC, MaxKovalets approved these changes

2016-12-22 19:38 UTC, JugerJuger approved these changes

2016-12-22 21:03 UTC, dmatsev commented on src/test/java/rv/atqc/gttesting/editmyprofiledata/US_EditMyProfileDataWithChrome.java
> +        driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
please use explicit waiter

2016-12-22 21:04 UTC, dmatsev commented on src/test/java/rv/atqc/gttesting/editmyprofiledata/US_EditMyProfileDataWithFirefox.java
> +        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
please use explicit waiter

2016-12-22 21:04 UTC, dmatsev reviewed
Please fix

2016-12-22 21:05 UTC, dmatsev requested changes
Please update your US branch

2016-12-23 16:03 UTC, dmatsev approved these changes

2016-12-25 13:28 UTC, dmatsev approved these changes

2016-12-26 12:42 UTC, merged