RVAT_720_722_VerifyExistenceOfDropdownSubMenuEvents
Social-projects-Rivne/GreenTourism_ATests pull request #89
Opened 2016-12-28 12:08 UTC by MelnykNikita

2016-12-28 12:20 UTC, TyshchenkoRoma commented on src/test/java/filterEventsOnTheMapByCategories/US_FilterEventsOnTheMapByCategoriesWithChrome.java
> +        Thread.sleep(2000);
I think that it is extra line.

2016-12-28 12:22 UTC, TyshchenkoRoma commented on src/test/java/filterEventsOnTheMapByCategories/US_FilterEventsOnTheMapByCategoriesWithChrome.java
> +        categoriesDropdownList = wait.until(ExpectedConditions.presenceOfElementLocated(categoriesLocator));
You can add ".click" at the end of this line.

2016-12-28 12:24 UTC, TyshchenkoRoma approved these changes

2016-12-28 17:31 UTC, dmatsev commented on src/test/java/filterEventsOnTheMapByCategories/US_FilterEventsOnTheMapByCategoriesWithChrome.java
> +        Thread.sleep(2000);
+1

2016-12-28 17:32 UTC, dmatsev commented on src/test/java/filterEventsOnTheMapByCategories/US_FilterEventsOnTheMapByCategoriesWithChrome.java
> +        if (element == null){
I don't understand this

2016-12-28 17:32 UTC, dmatsev requested changes
The same comments are valid for Firefox

2017-01-03 13:17 UTC, MaxKovalets approved these changes

2017-01-03 18:34 UTC, merged