Melnyk/rvat 725 726 verify title of dropdown sub menu events
Social-projects-Rivne/GreenTourism_ATests pull request #93
Opened 2016-12-28 14:11 UTC by MelnykNikita

2016-12-28 16:25 UTC, TyshchenkoRoma approved these changes

2016-12-28 17:17 UTC, dmatsev commented on pom.xml
> +			<version>3.0.1</version>
update this from dev branch

2016-12-28 17:18 UTC, dmatsev commented on src/test/java/filterEventsOnTheMapByCategories/US_FilterEventsOnTheMapByCategoriesWithChrome.java
> +    public class US_FilterEventsOnTheMapByCategoriesWithChrome {
format all document please

2016-12-28 17:21 UTC, dmatsev commented on src/test/java/filterEventsOnTheMapByCategories/US_FilterEventsOnTheMapByCategoriesWithChrome.java
> +            Thread.sleep(2000);
why we need it?

2016-12-28 17:21 UTC, dmatsev commented on src/test/java/filterEventsOnTheMapByCategories/US_FilterEventsOnTheMapByCategoriesWithChrome.java
> +
remove empty line

2016-12-28 17:22 UTC, dmatsev commented on src/test/java/filterEventsOnTheMapByCategories/US_FilterEventsOnTheMapByCategoriesWithChrome.java
> +            if (element == null){
I don't understand this logic. Explain please

2016-12-28 17:23 UTC, dmatsev requested changes
The same comments are valid for Firefox

2017-01-03 13:16 UTC, MaxKovalets approved these changes

2017-01-03 18:32 UTC, merged